pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 1023.0
    motor:
        id: 0
        init: 512
        min: 206
        max: 820

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 1023.0
    motor:
        id: 1
        init: 512
        min: 290
        max: 750
